[project]
name = "dcc-mcp-core"
version = "0.0.1"
description = "Foundational library for the DCC Model Context Protocol (MCP) ecosystem"
authors = [
    {name = "longhao",email = "hal.long@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.7,<4.0"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries",
    "Topic :: Multimedia :: Graphics :: 3D Modeling",
]
dependencies = [
    "loguru (>=0.7.3,<0.8.0)",
    "platformdirs (>=3,<4.0.0)"
]

[project.urls]
Homepage = "https://github.com/loonghao/dcc-mcp-core"
Issues = "https://github.com/loonghao/dcc-mcp-core/issues"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = "py37"
select = ["E", "F", "W", "I"]
ignore = []

[tool.ruff.isort]
known-first-party = ["dcc_mcp_core"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
