//! OpenAPI 3.1 document generated by `utoipa` at compile time.
//!
//! The proc-macro expansion reads the `ToSchema` derives we attached
//! to the request/response types in [`super::service`] and produces a
//! fully-typed [`utoipa::openapi::OpenApi`] document. Handlers annotate
//! their route signatures with `#[utoipa::path(...)]` in
//! [`super::router`], so the single source of truth for the contract
//! is the code itself — there is no hand-written JSON to drift from
//! the Rust types.
//!
//! Served verbatim from `GET /v1/openapi.json`.

use serde_json::Value;
use utoipa::OpenApi;

use super::errors::{ServiceError, ServiceErrorKind};
use super::readiness::ReadinessReport;
use super::service::{
    CallOutcome, CallRequest, ContextSnapshot, DescribeRequest, DescribeResponse, JobEvent,
    LoadSkillRequest, ProgressiveNextStep, PromptArgumentSpec, PromptContent, PromptGetResponse,
    PromptListEntry, PromptMessage, ResourceContent, ResourceEvent, ResourceListEntry,
    ResourceReadResponse, SearchRequest, SearchResponse, SkillLifecycleResponse, SkillListEntry,
    ToolSlug, UnloadSkillRequest,
};

/// Compile-time `ToSchema` registry for the REST skill API surface.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "dcc-mcp per-DCC REST skill API",
        description =
            "Per-DCC RESTful skill API (dcc-mcp-core issues #658 / #660). \
             Exposes the skills already discovered by a DCC process as a \
             stable, versioned HTTP API suitable for direct remote calls \
             and for indexing by the MCP gateway.",
        version = env!("CARGO_PKG_VERSION"),
    ),
    paths(
        super::router::op_healthz,
        super::router::op_readyz,
        super::router::op_openapi,
        super::router::op_list_skills,
        super::router::op_search,
        super::router::op_load_skill,
        super::router::op_unload_skill,
        super::router::op_describe,
        super::router::op_describe_path,
        super::router::op_call,
        super::router::op_dcc_backend_call,
        super::router::op_context,
        // #818 phase 1
        super::router::op_list_resources,
        super::router::op_read_resource,
        super::router::op_list_prompts,
        super::router::op_get_prompt,
        // #818 phase 1b
        super::router::op_resource_events,
        super::router::op_job_events,
        super::router::op_job_cancel,
    ),
    components(schemas(
        ServiceError,
        ServiceErrorKind,
        ReadinessReport,
        ToolSlug,
        SkillListEntry,
        ProgressiveNextStep,
        SearchRequest,
        SearchResponse,
        LoadSkillRequest,
        UnloadSkillRequest,
        SkillLifecycleResponse,
        DescribeRequest,
        DescribeResponse,
        CallRequest,
        CallOutcome,
        ContextSnapshot,
        // #818 phase 1
        ResourceListEntry,
        ResourceContent,
        ResourceReadResponse,
        PromptListEntry,
        PromptArgumentSpec,
        PromptMessage,
        PromptContent,
        PromptGetResponse,
        // #818 phase 1b
        ResourceEvent,
        JobEvent,
    )),
    tags(
        (name = "skills", description = "List / search / describe / call"),
        (name = "health",  description = "Liveness and readiness probes"),
        (name = "meta",    description = "API self-description"),
        (name = "resources", description = "MCP resources mirrored over REST (#818)"),
        (name = "prompts",   description = "MCP prompts mirrored over REST (#818)"),
        (name = "jobs",      description = "Async job lifecycle: SSE events + cancel (#818 phase 1b)"),
    ),
)]
pub struct SkillRestApiDoc;

/// Build a JSON value for the OpenAPI document.
///
/// `title` / `version` arguments are retained for backwards
/// compatibility but now overlay on top of the generated doc — useful
/// for embedders that want to publish under a branded name.
#[must_use]
pub fn build_openapi_document(server_title: &str, server_version: &str) -> Value {
    let mut doc = SkillRestApiDoc::openapi();
    doc.info.title = server_title.to_owned();
    doc.info.version = server_version.to_owned();
    serde_json::to_value(&doc).unwrap_or_else(|_| serde_json::json!({}))
}

/// Build the Scalar HTML API reference for the generated OpenAPI document.
#[must_use]
pub fn build_docs_html(server_title: &str, server_version: &str) -> String {
    let doc = build_openapi_document(server_title, server_version);
    build_docs_html_for_document(doc)
}

/// Build the Scalar HTML API reference for an already-customized OpenAPI document.
#[must_use]
pub fn build_docs_html_for_document(doc: Value) -> String {
    utoipa_scalar::Scalar::new(doc).to_html()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn openapi_document_lists_every_route() {
        let doc = build_openapi_document("test", "0.0.0");
        assert_eq!(doc["info"]["title"], "test");
        assert_eq!(doc["info"]["version"], "0.0.0");
        for p in [
            "/v1/skills",
            "/v1/search",
            "/v1/describe",
            "/v1/tools/{slug}",
            "/v1/call",
            "/v1/dcc/{dcc_type}/call",
            "/v1/context",
            "/v1/healthz",
            "/v1/readyz",
            "/v1/openapi.json",
            // #818 phase 1
            "/v1/resources",
            "/v1/resources/{uri}",
            "/v1/prompts",
            "/v1/prompts/{name}",
            // #818 phase 1b
            "/v1/resources/{uri}/events",
            "/v1/jobs/{id}/events",
            "/v1/jobs/{id}",
        ] {
            assert!(
                doc["paths"].get(p).is_some(),
                "OpenAPI doc missing path {p} — full doc: {doc:#}"
            );
        }
        // Error envelope schema must exist so clients can code-gen.
        assert!(
            doc["components"]["schemas"].get("ServiceError").is_some(),
            "ServiceError schema missing from generated doc"
        );
    }

    #[test]
    fn openapi_doc_respects_openapi_3_spec_version() {
        let doc = build_openapi_document("x", "1.0.0");
        let v = doc["openapi"].as_str().unwrap_or_default();
        assert!(v.starts_with("3."), "expected OpenAPI 3.x, got {v}");
    }

    /// Contract lock (PR A, MCP surface convergence): the REST invocation
    /// payload shape must stay stable so MCP `call_tool` (which routes
    /// through the same `call_service` code path on the gateway) and
    /// REST `/v1/call` callers can share a single request envelope.
    ///
    /// Any change to this test means a downstream-visible contract break
    /// and should be paired with an explicit CHANGELOG entry + migration
    /// note in `docs/guide/rest-api-surface.md`.
    #[test]
    fn call_request_schema_contract_is_stable() {
        let doc = build_openapi_document("x", "1.0.0");
        let schema = &doc["components"]["schemas"]["CallRequest"];
        assert!(
            schema.is_object(),
            "CallRequest schema missing from OpenAPI doc: {doc:#}"
        );
        let required: Vec<&str> = schema["required"]
            .as_array()
            .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();
        assert!(
            required.contains(&"tool_slug"),
            "CallRequest must require tool_slug; got required = {required:?}"
        );
        let props = schema["properties"]
            .as_object()
            .expect("CallRequest must declare properties");
        for field in ["tool_slug", "params"] {
            assert!(
                props.contains_key(field),
                "CallRequest is missing property {field}: {props:#?}"
            );
        }
    }

    /// Contract lock: the REST `/v1/call` success envelope must stay
    /// stable. Gateway MCP `call_tool` serialises the same `CallOutcome`
    /// so any drift here ripples through both transports.
    #[test]
    fn call_outcome_schema_contract_is_stable() {
        let doc = build_openapi_document("x", "1.0.0");
        let schema = &doc["components"]["schemas"]["CallOutcome"];
        assert!(
            schema.is_object(),
            "CallOutcome schema missing from OpenAPI doc: {doc:#}"
        );
        let props = schema["properties"]
            .as_object()
            .expect("CallOutcome must declare properties");
        for field in ["slug", "output", "validation_skipped"] {
            assert!(
                props.contains_key(field),
                "CallOutcome is missing property {field}: {props:#?}"
            );
        }
    }
}
