//! OpenAPI 3.1 document generated by `utoipa` at compile time.
//!
//! The proc-macro expansion reads the `ToSchema` derives we attached
//! to the request/response types in [`super::service`] and produces a
//! fully-typed [`utoipa::openapi::OpenApi`] document. Handlers annotate
//! their route signatures with `#[utoipa::path(...)]` in
//! [`super::router`], so the single source of truth for the contract
//! is the code itself — there is no hand-written JSON to drift from
//! the Rust types.
//!
//! Served verbatim from `GET /v1/openapi.json`.

use serde_json::Value;
use utoipa::OpenApi;

use super::errors::{ServiceError, ServiceErrorKind};
use super::readiness::ReadinessReport;
use super::service::{
    CallOutcome, CallRequest, ContextSnapshot, DescribeRequest, DescribeResponse, SearchRequest,
    SearchResponse, SkillListEntry, ToolSlug,
};

/// Compile-time `ToSchema` registry for the REST skill API surface.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "dcc-mcp per-DCC REST skill API",
        description =
            "Per-DCC RESTful skill API (dcc-mcp-core issues #658 / #660). \
             Exposes the skills already discovered by a DCC process as a \
             stable, versioned HTTP API suitable for direct remote calls \
             and for indexing by the MCP gateway.",
        version = env!("CARGO_PKG_VERSION"),
    ),
    paths(
        super::router::op_healthz,
        super::router::op_readyz,
        super::router::op_openapi,
        super::router::op_list_skills,
        super::router::op_search,
        super::router::op_describe,
        super::router::op_describe_path,
        super::router::op_call,
        super::router::op_context,
    ),
    components(schemas(
        ServiceError,
        ServiceErrorKind,
        ReadinessReport,
        ToolSlug,
        SkillListEntry,
        SearchRequest,
        SearchResponse,
        DescribeRequest,
        DescribeResponse,
        CallRequest,
        CallOutcome,
        ContextSnapshot,
    )),
    tags(
        (name = "skills", description = "List / search / describe / call"),
        (name = "health",  description = "Liveness and readiness probes"),
        (name = "meta",    description = "API self-description"),
    ),
)]
pub struct SkillRestApiDoc;

/// Build a JSON value for the OpenAPI document.
///
/// `title` / `version` arguments are retained for backwards
/// compatibility but now overlay on top of the generated doc — useful
/// for embedders that want to publish under a branded name.
#[must_use]
pub fn build_openapi_document(server_title: &str, server_version: &str) -> Value {
    let mut doc = SkillRestApiDoc::openapi();
    doc.info.title = server_title.to_owned();
    doc.info.version = server_version.to_owned();
    serde_json::to_value(&doc).unwrap_or_else(|_| serde_json::json!({}))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn openapi_document_lists_every_route() {
        let doc = build_openapi_document("test", "0.0.0");
        assert_eq!(doc["info"]["title"], "test");
        assert_eq!(doc["info"]["version"], "0.0.0");
        for p in [
            "/v1/skills",
            "/v1/search",
            "/v1/describe",
            "/v1/tools/{slug}",
            "/v1/call",
            "/v1/context",
            "/v1/healthz",
            "/v1/readyz",
            "/v1/openapi.json",
        ] {
            assert!(
                doc["paths"].get(p).is_some(),
                "OpenAPI doc missing path {p} — full doc: {doc:#}"
            );
        }
        // Error envelope schema must exist so clients can code-gen.
        assert!(
            doc["components"]["schemas"].get("ServiceError").is_some(),
            "ServiceError schema missing from generated doc"
        );
    }

    #[test]
    fn openapi_doc_respects_openapi_3_spec_version() {
        let doc = build_openapi_document("x", "1.0.0");
        let v = doc["openapi"].as_str().unwrap_or_default();
        assert!(v.starts_with("3."), "expected OpenAPI 3.x, got {v}");
    }
}
