"""Lazy public export metadata for :mod:`dcc_mcp_core`.

Keeping this data outside the package facade keeps ``__init__`` focused on
initialisation and lazy attribute resolution while preserving the public
top-level import contract.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Lazy import map: every public symbol and its source module.
#
# Format: "SymbolName": "source.module.path"
#
# Optional symbols (those wrapped in try/except ImportError in the old code)
# use the same format; __getattr__ returns None gracefully when the
# attribute does not exist in the source module.
# ---------------------------------------------------------------------------

_LAZY: dict[str, str] = {
    # Naming validators / constants (from _core)
    "ACTION_ID_RE": "dcc_mcp_core._core",
    "APP_AUTHOR": "dcc_mcp_core._core",
    "APP_NAME": "dcc_mcp_core._core",
    "DEFAULT_DCC": "dcc_mcp_core._core",
    "DEFAULT_LOG_FILE_PREFIX": "dcc_mcp_core._core",
    "DEFAULT_LOG_LEVEL": "dcc_mcp_core._core",
    "DEFAULT_LOG_MAX_FILES": "dcc_mcp_core._core",
    "DEFAULT_LOG_MAX_SIZE": "dcc_mcp_core._core",
    "DEFAULT_LOG_ROTATION": "dcc_mcp_core._core",
    "DEFAULT_MIME_TYPE": "dcc_mcp_core._core",
    "DEFAULT_VERSION": "dcc_mcp_core._core",
    "ENV_DISABLE_ACCUMULATED_SKILLS": "dcc_mcp_core._core",
    "ENV_LOG_DIR": "dcc_mcp_core._core",
    "ENV_LOG_FILE": "dcc_mcp_core._core",
    "ENV_LOG_FILE_PREFIX": "dcc_mcp_core._core",
    "ENV_LOG_LEVEL": "dcc_mcp_core._core",
    "ENV_LOG_MAX_FILES": "dcc_mcp_core._core",
    "ENV_LOG_MAX_SIZE": "dcc_mcp_core._core",
    "ENV_LOG_ROTATION": "dcc_mcp_core._core",
    "ENV_SKILL_PATHS": "dcc_mcp_core._core",
    "ENV_TEAM_SKILL_PATHS": "dcc_mcp_core._core",
    "ENV_USER_SKILL_PATHS": "dcc_mcp_core._core",
    "MAX_TOOL_NAME_LEN": "dcc_mcp_core._core",
    "SKILL_METADATA_DIR": "dcc_mcp_core._core",
    "SKILL_METADATA_FILE": "dcc_mcp_core._core",
    "SKILL_SCRIPTS_DIR": "dcc_mcp_core._core",
    "TOOL_NAME_RE": "dcc_mcp_core._core",
    # Sandbox / audit / IPC (from _core)
    "AuditEntry": "dcc_mcp_core._core",
    "AuditLog": "dcc_mcp_core._core",
    "AuditMiddleware": "dcc_mcp_core._core",
    "BooleanWrapper": "dcc_mcp_core._core",
    "BoundingBox": "dcc_mcp_core._core",
    "BridgeContext": "dcc_mcp_core._core",
    "BridgeRegistry": "dcc_mcp_core._core",
    "CaptureBackendKind": "dcc_mcp_core._core",
    "CaptureFrame": "dcc_mcp_core._core",
    "CaptureResult": "dcc_mcp_core._core",
    "CaptureTarget": "dcc_mcp_core._core",
    "Capturer": "dcc_mcp_core._core",
    "DccCapabilities": "dcc_mcp_core._core",
    "DccError": "dcc_mcp_core._core",
    "DccErrorCode": "dcc_mcp_core._core",
    "DccInfo": "dcc_mcp_core._core",
    "DccLinkFrame": "dcc_mcp_core._core",
    "EventBus": "dcc_mcp_core._core",
    "FileLoggingConfig": "dcc_mcp_core._core",
    "FileRef": "dcc_mcp_core._core",
    "FloatWrapper": "dcc_mcp_core._core",
    "FrameRange": "dcc_mcp_core._core",
    "GracefulIpcChannelAdapter": "dcc_mcp_core._core",
    "GuiExecutableHint": "dcc_mcp_core._core",
    "InputValidator": "dcc_mcp_core._core",
    "IntWrapper": "dcc_mcp_core._core",
    "IpcChannelAdapter": "dcc_mcp_core._core",
    "LoggingMiddleware": "dcc_mcp_core._core",
    "McpHttpConfig": "dcc_mcp_core._core",
    "McpHttpServer": "dcc_mcp_core._core",
    "McpServerHandle": "dcc_mcp_core._core",
    "ObjectTransform": "dcc_mcp_core._core",
    "PromptArgument": "dcc_mcp_core._core",
    "PromptDefinition": "dcc_mcp_core._core",
    "PyBufferPool": "dcc_mcp_core._core",
    "PyCrashRecoveryPolicy": "dcc_mcp_core._core",
    "PyDccLauncher": "dcc_mcp_core._core",
    "PyProcessMonitor": "dcc_mcp_core._core",
    "PyProcessWatcher": "dcc_mcp_core._core",
    "PyPumpedDispatcher": "dcc_mcp_core._core",
    "PySceneDataKind": "dcc_mcp_core._core",
    "PySharedBuffer": "dcc_mcp_core._core",
    "PySharedSceneBuffer": "dcc_mcp_core._core",
    "PyStandaloneDispatcher": "dcc_mcp_core._core",
    "RateLimitMiddleware": "dcc_mcp_core._core",
    "ReadinessProbe": "dcc_mcp_core._core",
    "AdapterReadinessBinder": "dcc_mcp_core.readiness",
    "RecordingGuard": "dcc_mcp_core._core",
    "RenderOutput": "dcc_mcp_core._core",
    "ResourceAnnotations": "dcc_mcp_core._core",
    "ResourceDefinition": "dcc_mcp_core._core",
    "ResourceTemplateDefinition": "dcc_mcp_core._core",
    "RetryPolicy": "dcc_mcp_core._core",
    "SandboxContext": "dcc_mcp_core._core",
    "SandboxPolicy": "dcc_mcp_core._core",
    "SceneInfo": "dcc_mcp_core._core",
    "SceneNode": "dcc_mcp_core._core",
    "SceneObject": "dcc_mcp_core._core",
    "SceneStatistics": "dcc_mcp_core._core",
    "ScriptLanguage": "dcc_mcp_core._core",
    "ScriptResult": "dcc_mcp_core._core",
    "SdfPath": "dcc_mcp_core._core",
    "SemVer": "dcc_mcp_core._core",
    "SerializeFormat": "dcc_mcp_core._core",
    "ServiceEntry": "dcc_mcp_core._core",
    "ServiceStatus": "dcc_mcp_core._core",
    "SkillCatalog": "dcc_mcp_core._core",
    "SkillFeedback": "dcc_mcp_core._core",
    "SkillGroup": "dcc_mcp_core._core",
    "SkillMetadata": "dcc_mcp_core._core",
    "SkillRuntimeDescriptor": "dcc_mcp_core._core",
    "SkillRuntimeKind": "dcc_mcp_core._core",
    "SkillRuntimeReport": "dcc_mcp_core._core",
    "SkillRuntimeState": "dcc_mcp_core._core",
    "SkillRuntimeSummary": "dcc_mcp_core._core",
    "SkillScanner": "dcc_mcp_core._core",
    "SkillScope": "dcc_mcp_core._core",
    "SkillSummary": "dcc_mcp_core._core",
    "SkillValidationIssue": "dcc_mcp_core._core",
    "SkillValidationReport": "dcc_mcp_core._core",
    "SkillVersionEntry": "dcc_mcp_core._core",
    "SkillVersionManifest": "dcc_mcp_core._core",
    "SkillWatcher": "dcc_mcp_core._core",
    "SocketServerAdapter": "dcc_mcp_core._core",
    "StepPolicy": "dcc_mcp_core._core",
    "StringWrapper": "dcc_mcp_core._core",
    "TelemetryConfig": "dcc_mcp_core._core",
    "TimingMiddleware": "dcc_mcp_core._core",
    "ToolAnnotations": "dcc_mcp_core._core",
    "ToolDeclaration": "dcc_mcp_core._core",
    "ToolDefinition": "dcc_mcp_core._core",
    "ToolDispatcher": "dcc_mcp_core._core",
    "ToolMetrics": "dcc_mcp_core._core",
    "ToolPipeline": "dcc_mcp_core._core",
    "ToolRecorder": "dcc_mcp_core._core",
    "ToolRegistry": "dcc_mcp_core._core",
    "ToolResult": "dcc_mcp_core._core",
    "ToolValidator": "dcc_mcp_core._core",
    "TransportAddress": "dcc_mcp_core._core",
    "TransportScheme": "dcc_mcp_core._core",
    "UsdPrim": "dcc_mcp_core._core",
    "UsdStage": "dcc_mcp_core._core",
    "UsdProjectResource": "dcc_mcp_core.usd_resources",
    "UsdProjectResourceProvider": "dcc_mcp_core.usd_resources",
    "VersionConstraint": "dcc_mcp_core._core",
    "VersionedRegistry": "dcc_mcp_core._core",
    "VtValue": "dcc_mcp_core._core",
    "WindowFinder": "dcc_mcp_core._core",
    "WindowInfo": "dcc_mcp_core._core",
    "WorkflowSpec": "dcc_mcp_core._core",
    "WorkflowStatus": "dcc_mcp_core._core",
    "WorkflowStep": "dcc_mcp_core._core",
    "WorkspaceRoots": "dcc_mcp_core._core",
    "USD_ASSETS_URI": "dcc_mcp_core.usd_resources",
    "USD_BINARY_MIME": "dcc_mcp_core.usd_resources",
    "USD_JSON_MIME": "dcc_mcp_core.usd_resources",
    "USD_LAYERS_URI": "dcc_mcp_core.usd_resources",
    "USD_MARKDOWN_MIME": "dcc_mcp_core.usd_resources",
    "USD_MATERIALS_URI": "dcc_mcp_core.usd_resources",
    "USD_PACKAGE_MIME": "dcc_mcp_core.usd_resources",
    "USD_PACKAGES_URI": "dcc_mcp_core.usd_resources",
    "USD_RESOURCE_SCHEME": "dcc_mcp_core.usd_resources",
    "USD_SNAPSHOTS_URI": "dcc_mcp_core.usd_resources",
    "USD_STAGE_URI": "dcc_mcp_core.usd_resources",
    "USD_TEXT_MIME": "dcc_mcp_core.usd_resources",
    "USD_VALIDATION_URI": "dcc_mcp_core.usd_resources",
    "DEFAULT_FIRST_PUMP_TIMEOUT_SECS": "dcc_mcp_core.readiness",
    "READINESS_ALL_BITS": "dcc_mcp_core.readiness",
    "READINESS_BASE_BITS": "dcc_mcp_core.readiness",
    "READINESS_EXECUTION_BITS": "dcc_mcp_core.readiness",
    # Functions from _core
    "artefact_get_bytes": "dcc_mcp_core._core",
    "artefact_list": "dcc_mcp_core._core",
    "artefact_put_bytes": "dcc_mcp_core._core",
    "artefact_put_file": "dcc_mcp_core._core",
    "copy_skill_to_team_dir": "dcc_mcp_core._core",
    "copy_skill_to_user_dir": "dcc_mcp_core._core",
    "correct_python_executable": "dcc_mcp_core._core",
    "create_skill_server": "dcc_mcp_core._core",
    "deserialize_result": "dcc_mcp_core._core",
    "error_result": "dcc_mcp_core._core",
    "expand_transitive_dependencies": "dcc_mcp_core._core",
    "flush_logs": "dcc_mcp_core._core",
    "from_exception": "dcc_mcp_core._core",
    "gc_orphans": "dcc_mcp_core._core",
    "get_app_skill_paths_from_env": "dcc_mcp_core._core",
    "get_app_team_skill_paths_from_env": "dcc_mcp_core._core",
    "get_app_user_skill_paths_from_env": "dcc_mcp_core._core",
    "get_bridge_context": "dcc_mcp_core._core",
    "get_config_dir": "dcc_mcp_core._core",
    "get_data_dir": "dcc_mcp_core._core",
    "get_log_dir": "dcc_mcp_core._core",
    "get_local_skills_dir": "dcc_mcp_core._core",
    "get_platform_dir": "dcc_mcp_core._core",
    "get_skill_feedback": "dcc_mcp_core._core",
    "get_skill_paths_from_env": "dcc_mcp_core._core",
    "get_skill_version_manifest": "dcc_mcp_core._core",
    "get_skills_dir": "dcc_mcp_core._core",
    "get_team_skill_paths_from_env": "dcc_mcp_core._core",
    "get_team_skills_dir": "dcc_mcp_core._core",
    "get_tools_dir": "dcc_mcp_core._core",
    "get_user_skill_paths_from_env": "dcc_mcp_core._core",
    "get_user_skills_dir": "dcc_mcp_core._core",
    "hmac_sha256_hex": "dcc_mcp_core._core",
    "init_file_logging": "dcc_mcp_core._core",
    "is_gui_executable": "dcc_mcp_core._core",
    "is_telemetry_initialized": "dcc_mcp_core._core",
    "json_dumps": "dcc_mcp_core.skills_helper",
    "json_loads": "dcc_mcp_core.skills_helper",
    "mpu_to_units": "dcc_mcp_core._core",
    "parse_schedules_yaml": "dcc_mcp_core._core",
    "parse_skill_md": "dcc_mcp_core._core",
    "record_skill_feedback": "dcc_mcp_core._core",
    "register_bridge": "dcc_mcp_core._core",
    "resolve_dependencies": "dcc_mcp_core._core",
    "scan_and_load": "dcc_mcp_core._core",
    "scan_and_load_lenient": "dcc_mcp_core._core",
    "scan_and_load_strict": "dcc_mcp_core._core",
    "scan_and_load_team": "dcc_mcp_core._core",
    "scan_and_load_team_lenient": "dcc_mcp_core._core",
    "scan_and_load_user": "dcc_mcp_core._core",
    "scan_and_load_user_lenient": "dcc_mcp_core._core",
    "scan_skill_paths": "dcc_mcp_core._core",
    "scene_info_json_to_stage": "dcc_mcp_core._core",
    "serialize_result": "dcc_mcp_core._core",
    "shutdown_file_logging": "dcc_mcp_core._core",
    "shutdown_telemetry": "dcc_mcp_core._core",
    "stage_to_scene_info_json": "dcc_mcp_core._core",
    "success_result": "dcc_mcp_core._core",
    "units_to_mpu": "dcc_mcp_core._core",
    "unwrap_parameters": "dcc_mcp_core._core",
    "unwrap_value": "dcc_mcp_core._core",
    "validate_action_id": "dcc_mcp_core._core",
    "validate_action_result": "dcc_mcp_core._core",
    "validate_dependencies": "dcc_mcp_core._core",
    "validate_skill": "dcc_mcp_core._core",
    "validate_tool_name": "dcc_mcp_core._core",
    "verify_hub_signature_256": "dcc_mcp_core._core",
    "wrap_value": "dcc_mcp_core._core",
    "yaml_dumps": "dcc_mcp_core.skills_helper",
    "yaml_loads": "dcc_mcp_core.skills_helper",
    # Optional _core symbols (try/except ImportError in old code)
    # Returns None when the feature is not compiled in.
    "BackoffKind": "dcc_mcp_core._core",
    "OutputCapture": "dcc_mcp_core._core",
    "PromptHandle": "dcc_mcp_core._core",
    "ResourceHandle": "dcc_mcp_core._core",
    "ScheduleSpec": "dcc_mcp_core._core",
    "SessionEventBuffer": "dcc_mcp_core._core",
    "ToolSpec": "dcc_mcp_core._core",
    "TriggerSpec": "dcc_mcp_core._core",
    # _server collaborators
    "AdaptivePumpPolicy": "dcc_mcp_core._server",
    "AdaptivePumpStats": "dcc_mcp_core._server",
    "BaseDccCallableDispatcher": "dcc_mcp_core._server",
    "BaseDccCallableDispatcherFull": "dcc_mcp_core._server",
    "BaseDccPump": "dcc_mcp_core._server",
    "DeferredToolResult": "dcc_mcp_core._server",
    "DebugPathMapping": "dcc_mcp_core.adapter_contracts",
    "DebugSessionDescriptor": "dcc_mcp_core.adapter_contracts",
    "DebugSessionStatus": "dcc_mcp_core.adapter_contracts",
    "AppUiAuditRecord": "dcc_mcp_core.adapter_contracts",
    "AppUiPolicy": "dcc_mcp_core.adapter_contracts",
    "DEFAULT_UI_JOB_TIMEOUT_MS": "dcc_mcp_core._server",
    "DispatcherErrorCode": "dcc_mcp_core._server",
    "HostExecutionBridge": "dcc_mcp_core._server",
    "HostPumpController": "dcc_mcp_core._server",
    "HostPumpSnapshot": "dcc_mcp_core._server",
    "HostPumpTimerAdapter": "dcc_mcp_core._server",
    "HostUiDispatcherBase": "dcc_mcp_core._server",
    "ENV_EXCLUDE_STUBS_FROM_TOOLS_LIST": "dcc_mcp_core._server",
    "HostUiJobEntry": "dcc_mcp_core._server",
    "ToolsListStubPolicy": "dcc_mcp_core._server",
    "UiActionKind": "dcc_mcp_core.adapter_contracts",
    "UiActionRequest": "dcc_mcp_core.adapter_contracts",
    "UiActionResult": "dcc_mcp_core.adapter_contracts",
    "UiArtifactRef": "dcc_mcp_core.adapter_contracts",
    "UiBounds": "dcc_mcp_core.adapter_contracts",
    "UiControlNode": "dcc_mcp_core.adapter_contracts",
    "UiErrorCode": "dcc_mcp_core.adapter_contracts",
    "UiFindRequest": "dcc_mcp_core.adapter_contracts",
    "UiSnapshot": "dcc_mcp_core.adapter_contracts",
    "UiWaitCondition": "dcc_mcp_core.adapter_contracts",
    "UiWaitConditionKind": "dcc_mcp_core.adapter_contracts",
    "UiWaitResult": "dcc_mcp_core.adapter_contracts",
    "apply_tools_list_stub_policy": "dcc_mcp_core._server",
    "dcc_exclude_stubs_env_name": "dcc_mcp_core._server",
    "env_truthy": "dcc_mcp_core._server",
    "resolve_tools_list_stub_policy": "dcc_mcp_core._server",
    "InProcessCallableDispatcher": "dcc_mcp_core._server",
    "current_host_ui_job": "dcc_mcp_core._server",
    "host_ui_outcome": "dcc_mcp_core._server",
    "normalize_affinity": "dcc_mcp_core._server",
    "InProcessExecutionContext": "dcc_mcp_core._server",
    "JobEntry": "dcc_mcp_core._server",
    "JobOutcome": "dcc_mcp_core._server",
    "ManualHostTimerAdapter": "dcc_mcp_core._server",
    "MinimalModeConfig": "dcc_mcp_core._server",
    "PendingEnvelope": "dcc_mcp_core._server",
    "QtHostTimerAdapter": "dcc_mcp_core._server",
    "ThreadedHostTimerAdapter": "dcc_mcp_core._server",
    "current_callable_job": "dcc_mcp_core._server",
    # DccServerOptions (issue #850)
    "BridgeExecution": "dcc_mcp_core._server.options",
    "DccServerOptions": "dcc_mcp_core._server.options",
    "DiagnosticsOptions": "dcc_mcp_core._server.options",
    "DispatcherExecution": "dcc_mcp_core._server.options",
    "ExecutionOptions": "dcc_mcp_core._server.options",
    "GatewayOptions": "dcc_mcp_core._server.options",
    "InlineExecution": "dcc_mcp_core._server.options",
    "ObservabilityOptions": "dcc_mcp_core._server.options",
    "StandaloneMainThreadExecution": "dcc_mcp_core._server.options",
    # Lifecycle hooks (issue #1337)
    "HookContext": "dcc_mcp_core.lifecycle_hooks",
    "HookDeny": "dcc_mcp_core.lifecycle_hooks",
    "HookEvent": "dcc_mcp_core.lifecycle_hooks",
    "LifecycleHooks": "dcc_mcp_core.lifecycle_hooks",
    # Escape-hatch demotion policy (issue #1325)
    "EscapeHatchInvocation": "dcc_mcp_core.escape_hatch_policy",
    "EscapeHatchPolicy": "dcc_mcp_core.escape_hatch_policy",
    # Capability graph (issue #1336)
    "CapabilityEdge": "dcc_mcp_core.capability_graph",
    "CapabilityGraph": "dcc_mcp_core.capability_graph",
    "EdgeKind": "dcc_mcp_core.capability_graph",
    # Agent memory layers (issue #1334)
    "InMemoryMemoryStore": "dcc_mcp_core.agent_memory",
    "MemoryEntry": "dcc_mcp_core.agent_memory",
    "MemoryLayer": "dcc_mcp_core.agent_memory",
    "MemoryQuery": "dcc_mcp_core.agent_memory",
    "MemoryRecorder": "dcc_mcp_core.agent_memory",
    # Semantic skill index (issue #1333)
    "LexicalSkillIndex": "dcc_mcp_core.semantic_skill_index",
    "RrfFusionIndex": "dcc_mcp_core.semantic_skill_index",
    "SkillDocument": "dcc_mcp_core.semantic_skill_index",
    "SkillSearchHit": "dcc_mcp_core.semantic_skill_index",
    # Vector skill index (issue #1393) — zero-dep default, optional ONNX extra
    "Embedder": "dcc_mcp_core.vector_embedder",
    "EmbedderError": "dcc_mcp_core.vector_embedder",
    "HashedEmbedder": "dcc_mcp_core.vector_embedder",
    "OnnxEmbedder": "dcc_mcp_core.vector_embedder",
    "InMemoryVectorStore": "dcc_mcp_core.vector_skill_index",
    "VectorSkillIndex": "dcc_mcp_core.vector_skill_index",
    "VectorStore": "dcc_mcp_core.vector_skill_index",
    # Qt UI inspector (issue #1332) - opt-in default capability
    "qt_describe_widget": "dcc_mcp_core.skills.qt_ui_inspector",
    "qt_find_widgets": "dcc_mcp_core.skills.qt_ui_inspector",
    "qt_list_windows": "dcc_mcp_core.skills.qt_ui_inspector",
    "qt_snapshot_tree": "dcc_mcp_core.skills.qt_ui_inspector",
    "qt_wait_for_widget": "dcc_mcp_core.skills.qt_ui_inspector",
    "register_qt_ui_inspector": "dcc_mcp_core.skills.qt_ui_inspector",
    "register_all_builtin_skills": "dcc_mcp_core.skills.builtin",
    # DccServerBase + factory
    "DccServerBase": "dcc_mcp_core.server_base",
    "create_dcc_server": "dcc_mcp_core.factory",
    "get_server_instance": "dcc_mcp_core.factory",
    "make_start_stop": "dcc_mcp_core.factory",
    "start_embedded_dcc_server": "dcc_mcp_core.factory",
    "DccGatewayElection": "dcc_mcp_core.gateway_election",
    "DccSkillHotReloader": "dcc_mcp_core.hotreload",
    "read_custom_skill_paths": "dcc_mcp_core.admin_sqlite_lane",
    "resolve_admin_db_path": "dcc_mcp_core.admin_sqlite_lane",
    # Pure-Python constants
    "CAPABILITY_KEYS": "dcc_mcp_core.adapters",
    "WEBVIEW_DEFAULT_CAPABILITIES": "dcc_mcp_core.adapters",
    "WebViewAdapter": "dcc_mcp_core.adapters",
    "WebViewContext": "dcc_mcp_core.adapters",
    "CATEGORY_DIAGNOSTICS": "dcc_mcp_core.constants",
    "CATEGORY_DOCS": "dcc_mcp_core.constants",
    "CATEGORY_FEEDBACK": "dcc_mcp_core.constants",
    "CATEGORY_GENERAL": "dcc_mcp_core.constants",
    "CATEGORY_INTROSPECT": "dcc_mcp_core.constants",
    "CATEGORY_RECIPES": "dcc_mcp_core.constants",
    "CATEGORY_WORKFLOWS": "dcc_mcp_core.constants",
    "LAYER_DOMAIN": "dcc_mcp_core.constants",
    "LAYER_EXAMPLE": "dcc_mcp_core.constants",
    "LAYER_INFRASTRUCTURE": "dcc_mcp_core.constants",
    "LAYER_THIN_HARNESS": "dcc_mcp_core.constants",
    "METADATA_DCC_KEY": "dcc_mcp_core.constants",
    "METADATA_DCC_MCP": "dcc_mcp_core.constants",
    "METADATA_EXAMPLES_KEY": "dcc_mcp_core.constants",
    "METADATA_EXTERNAL_DEPS_KEY": "dcc_mcp_core.constants",
    "METADATA_GROUPS_KEY": "dcc_mcp_core.constants",
    "METADATA_LAYER_KEY": "dcc_mcp_core.constants",
    "METADATA_PROMPTS_KEY": "dcc_mcp_core.constants",
    "METADATA_RECIPES_KEY": "dcc_mcp_core.constants",
    "METADATA_SEARCH_HINT_KEY": "dcc_mcp_core.constants",
    "METADATA_SKILL_REFERENCE_DOCS_KEY": "dcc_mcp_core.constants",
    "METADATA_TAGS_KEY": "dcc_mcp_core.constants",
    "METADATA_TOOLS_KEY": "dcc_mcp_core.constants",
    "METADATA_VERSION_KEY": "dcc_mcp_core.constants",
    "METADATA_WORKFLOWS_KEY": "dcc_mcp_core.constants",
    "PROJECT_DIR_NAME": "dcc_mcp_core.project",
    "PROJECT_STATE_FILE": "dcc_mcp_core.project",
    # Pure-Python sub-module symbols
    "AdapterInstructionSet": "dcc_mcp_core.adapter_context",
    "DccContextSnapshot": "dcc_mcp_core.adapter_context",
    "DccToolsetProfile": "dcc_mcp_core.adapter_context",
    "ResponseShapePolicy": "dcc_mcp_core.adapter_context",
    "ToolsetProfileRegistry": "dcc_mcp_core.adapter_context",
    "VisualFeedbackPolicy": "dcc_mcp_core.adapter_context",
    "append_context_snapshot": "dcc_mcp_core.adapter_context",
    "build_visual_feedback_context": "dcc_mcp_core.adapter_context",
    "register_adapter_instruction_resources": "dcc_mcp_core.adapter_context",
    "shape_response": "dcc_mcp_core.adapter_context",
    "ApiKeyConfig": "dcc_mcp_core.auth",
    "CimdDocument": "dcc_mcp_core.auth",
    "OAuthConfig": "dcc_mcp_core.auth",
    "TokenValidationError": "dcc_mcp_core.auth",
    "generate_api_key": "dcc_mcp_core.auth",
    "validate_bearer_token": "dcc_mcp_core.auth",
    "EvalContext": "dcc_mcp_core.batch",
    "batch_dispatch": "dcc_mcp_core.batch",
    "BridgeConnectionError": "dcc_mcp_core.bridge",
    "BridgeError": "dcc_mcp_core.bridge",
    "BridgeFallbackClient": "dcc_mcp_core.bridge",
    "BridgeRetryPolicy": "dcc_mcp_core.bridge",
    "BridgeRpcError": "dcc_mcp_core.bridge",
    "BridgeTimeoutError": "dcc_mcp_core.bridge",
    "BridgeTransportStrategy": "dcc_mcp_core.bridge",
    "DccBridge": "dcc_mcp_core.bridge",
    "ReverseBridgeRequest": "dcc_mcp_core.bridge",
    "ReverseBridgeSession": "dcc_mcp_core.bridge",
    "CancelToken": "dcc_mcp_core.cancellation",
    "CancelledError": "dcc_mcp_core.cancellation",
    "JobHandle": "dcc_mcp_core.cancellation",
    "check_cancelled": "dcc_mcp_core.cancellation",
    "check_dcc_cancelled": "dcc_mcp_core.cancellation",
    "current_cancel_token": "dcc_mcp_core.cancellation",
    "current_job": "dcc_mcp_core.cancellation",
    "reset_cancel_token": "dcc_mcp_core.cancellation",
    "reset_current_job": "dcc_mcp_core.cancellation",
    "set_cancel_token": "dcc_mcp_core.cancellation",
    "set_current_job": "dcc_mcp_core.cancellation",
    "CheckpointStore": "dcc_mcp_core.checkpoint",
    "checkpoint_every": "dcc_mcp_core.checkpoint",
    "clear_checkpoint": "dcc_mcp_core.checkpoint",
    "configure_checkpoint_store": "dcc_mcp_core.checkpoint",
    "get_checkpoint": "dcc_mcp_core.checkpoint",
    "list_checkpoints": "dcc_mcp_core.checkpoint",
    "register_checkpoint_tools": "dcc_mcp_core.checkpoint",
    "save_checkpoint": "dcc_mcp_core.checkpoint",
    "DccApiCatalog": "dcc_mcp_core.dcc_api_executor",
    "DccApiExecutor": "dcc_mcp_core.dcc_api_executor",
    "register_dcc_api_executor": "dcc_mcp_core.dcc_api_executor",
    "register_diagnostic_handlers": "dcc_mcp_core.dcc_server",
    "register_diagnostic_mcp_tools": "dcc_mcp_core.dcc_server",
    "get_builtin_docs_uris": "dcc_mcp_core.docs_resources",
    "get_docs_content": "dcc_mcp_core.docs_resources",
    "register_docs_resource": "dcc_mcp_core.docs_resources",
    "register_docs_resources_from_dir": "dcc_mcp_core.docs_resources",
    "register_docs_server": "dcc_mcp_core.docs_resources",
    "ElicitationMode": "dcc_mcp_core.elicitation",
    "ElicitationRequest": "dcc_mcp_core.elicitation",
    "ElicitationResponse": "dcc_mcp_core.elicitation",
    "FormElicitation": "dcc_mcp_core.elicitation",
    "UrlElicitation": "dcc_mcp_core.elicitation",
    "elicit_form": "dcc_mcp_core.elicitation",
    "elicit_form_sync": "dcc_mcp_core.elicitation",
    "elicit_url": "dcc_mcp_core.elicitation",
    "clear_feedback": "dcc_mcp_core.feedback",
    "extract_rationale": "dcc_mcp_core.feedback",
    "get_feedback_entries": "dcc_mcp_core.feedback",
    "make_rationale_meta": "dcc_mcp_core.feedback",
    "register_feedback_tool": "dcc_mcp_core.feedback",
    "DccBlockedCall": "dcc_mcp_core.guardrails",
    "DccGuardrailError": "dcc_mcp_core.guardrails",
    "DccWeakSandbox": "dcc_mcp_core.guardrails",
    "introspect_eval": "dcc_mcp_core.introspect",
    "introspect_list_module": "dcc_mcp_core.introspect",
    "introspect_search": "dcc_mcp_core.introspect",
    "introspect_signature": "dcc_mcp_core.introspect",
    "register_introspect_tools": "dcc_mcp_core.introspect",
    "MetadataExtensionRegistration": "dcc_mcp_core.metadata_registration",
    "MetadataExtensionResult": "dcc_mcp_core.metadata_registration",
    "MetadataRegistrationReport": "dcc_mcp_core.metadata_registration",
    "default_metadata_extension_registrations": "dcc_mcp_core.metadata_registration",
    "imported_metadata_extension": "dcc_mcp_core.metadata_registration",
    "metadata_extension": "dcc_mcp_core.metadata_registration",
    "register_metadata_driven_tools": "dcc_mcp_core.metadata_registration",
    "PluginManifest": "dcc_mcp_core.plugin_manifest",
    "build_plugin_manifest": "dcc_mcp_core.plugin_manifest",
    "build_usd_project_resources": "dcc_mcp_core.usd_resources",
    "export_plugin_manifest": "dcc_mcp_core.plugin_manifest",
    "DccProject": "dcc_mcp_core.project",
    "ProjectState": "dcc_mcp_core.project",
    "register_project_tools": "dcc_mcp_core.project",
    "RecipeDefinition": "dcc_mcp_core.recipes",
    "find_recipe_entry": "dcc_mcp_core.recipes",
    "get_recipe_content": "dcc_mcp_core.recipes",
    "get_recipes_path": "dcc_mcp_core.recipes",
    "get_recipes_paths": "dcc_mcp_core.recipes",
    "list_recipe_entries": "dcc_mcp_core.recipes",
    "load_recipe_pack": "dcc_mcp_core.recipes",
    "parse_recipe_anchors": "dcc_mcp_core.recipes",
    "register_recipes_tools": "dcc_mcp_core.recipes",
    "validate_recipe_inputs": "dcc_mcp_core.recipes",
    "register_skill_reference_docs_tools": "dcc_mcp_core.skill_reference_docs",
    "register_usd_project_resources": "dcc_mcp_core.usd_resources",
    "RichContent": "dcc_mcp_core.rich_content",
    "RichContentKind": "dcc_mcp_core.rich_content",
    "attach_rich_content": "dcc_mcp_core.rich_content",
    "skill_success_with_chart": "dcc_mcp_core.rich_content",
    "skill_success_with_image": "dcc_mcp_core.rich_content",
    "skill_success_with_table": "dcc_mcp_core.rich_content",
    "derive_parameters_schema": "dcc_mcp_core.schema",
    "derive_schema": "dcc_mcp_core.schema",
    "schema_from_doc": "dcc_mcp_core.schema",
    "tool_spec_from_callable": "dcc_mcp_core.schema",
    "FileBackedScriptExecutionParams": "dcc_mcp_core.script_execution",
    "ScriptExecutionCapture": "dcc_mcp_core.script_execution",
    "ScriptExecutionParams": "dcc_mcp_core.script_execution",
    "ScriptExecutionResult": "dcc_mcp_core.script_execution",
    "ScriptExecutionSerializationError": "dcc_mcp_core.script_execution",
    "allow_script_materialization_root": "dcc_mcp_core.script_execution",
    "MaterializedScript": "dcc_mcp_core.script_materialization",
    "cleanup_materialized_scripts": "dcc_mcp_core.script_materialization",
    "default_script_materialization_root": "dcc_mcp_core.script_materialization",
    "materialize_script": "dcc_mcp_core.script_materialization",
    "register_script_materialization_tools": "dcc_mcp_core.script_materialization_tools",
    "sanitize_materialization_segment": "dcc_mcp_core.script_materialization",
    "normalize_file_backed_script_execution_params": "dcc_mcp_core.script_execution",
    "normalize_script_execution_params": "dcc_mcp_core.script_execution",
    "validate_script_file_path": "dcc_mcp_core.script_execution",
    "build_sidecar_command": "dcc_mcp_core.install_lifecycle",
    "default_registry_dir": "dcc_mcp_core.install_lifecycle",
    "inspect_install_root": "dcc_mcp_core.install_lifecycle",
    "launch_sidecar": "dcc_mcp_core.install_lifecycle",
    "plan_runtime_updates": "dcc_mcp_core.install_lifecycle",
    "query_runtime_state": "dcc_mcp_core.install_lifecycle",
    "resolve_deployment_layout": "dcc_mcp_core.install_lifecycle",
    "safe_remove_tree": "dcc_mcp_core.install_lifecycle",
    "safe_replace_tree": "dcc_mcp_core.install_lifecycle",
    "stop_runtime_entries": "dcc_mcp_core.install_lifecycle",
    "normalize_tool_arguments": "dcc_mcp_core.host",
    "normalize_tool_meta": "dcc_mcp_core.host",
    "SidecarActionDispatcher": "dcc_mcp_core.sidecar",
    "SidecarDispatchRequest": "dcc_mcp_core.sidecar",
    "ERROR_DISPATCH_FAILED": "dcc_mcp_core.sidecar",
    "ERROR_NO_SOURCE_FILE": "dcc_mcp_core.sidecar",
    "ERROR_PAYLOAD_MALFORMED": "dcc_mcp_core.sidecar",
    "ERROR_SERVER_NOT_RUNNING": "dcc_mcp_core.sidecar",
    "ERROR_UNKNOWN_ACTION": "dcc_mcp_core.sidecar",
    "readiness_report_subset": "dcc_mcp_core.readiness",
    "SkillHelperError": "dcc_mcp_core.skills_helper",
    "skill_error_from_exception": "dcc_mcp_core.skills_helper",
    # skill helpers (pure-Python, used inside skill scripts)
    "get_bundled_skill_paths": "dcc_mcp_core.skill",
    "get_bundled_skills_dir": "dcc_mcp_core.skill",
    "run_main": "dcc_mcp_core.skill",
    "skill_entry": "dcc_mcp_core.skill",
    "skill_error": "dcc_mcp_core.skill",
    "skill_error_with_trace": "dcc_mcp_core.skill",
    "skill_exception": "dcc_mcp_core.skill",
    "skill_success": "dcc_mcp_core.skill",
    "skill_warning": "dcc_mcp_core.skill",
    "SceneStats": "dcc_mcp_core.verifier",
    "WorkflowTask": "dcc_mcp_core.workflow_yaml",
    "WorkflowYaml": "dcc_mcp_core.workflow_yaml",
    "get_workflow_path": "dcc_mcp_core.workflow_yaml",
    "load_workflow_yaml": "dcc_mcp_core.workflow_yaml",
    "register_workflow_yaml_tools": "dcc_mcp_core.workflow_yaml",
}

# Optional symbols that may not exist in all wheel builds; return None instead of AttributeError.
_OPTIONAL: frozenset[str] = frozenset(
    {
        "BackoffKind",
        "OutputCapture",
        "PromptHandle",
        "ResourceHandle",
        "ScheduleSpec",
        "SessionEventBuffer",
        "ToolSpec",
        "TriggerSpec",
    }
)


def _public_export_sort_key(name: str) -> tuple[int, str]:
    """Preserve historical ``__all__`` ordering without duplicating names."""
    if name.startswith("__"):
        group = 2
    elif name[:1].islower():
        group = 3
    elif name.isupper():
        group = 0
    else:
        group = 1
    return (group, name)


PUBLIC_EXPORTS: list[str] = sorted(
    [*_LAZY, "__author__", "__version__"],
    key=_public_export_sort_key,
)
